import React, { useState } from 'react';
import type { RGB } from '../utils/colors';
import { rgbToHex, rgbToOklch, oklchToString } from '../utils/colors';
import { Check, Copy, Code, Paintbrush, Braces, Atom, Download } from 'lucide-react';

interface ExportPanelProps {
  palette: RGB[];
}

type TabId = 'tailwind' | 'css' | 'oklch' | 'json';

// Single source of truth for naming — consistent lumina-N across all formats
const getColorName = (index: number) => `lumina-${index + 1}`;

// ─── Generators ───────────────────────────────────────────────────────────────

const generateTailwind = (palette: RGB[]) => {
  const lines = palette
    .map((rgb, i) => `        '${getColorName(i)}': '${rgbToHex(rgb[0], rgb[1], rgb[2])}',`)
    .join('\n');
  return `module.exports = {\n  theme: {\n    extend: {\n      colors: {\n${lines}\n      }\n    }\n  }\n}`;
};

const generateCSS = (palette: RGB[]) => {
  const lines = palette
    .map((rgb, i) => `  --${getColorName(i)}: ${rgbToHex(rgb[0], rgb[1], rgb[2])};`)
    .join('\n');
  return `:root {\n${lines}\n}`;
};

const generateOKLCH = (palette: RGB[]) => {
  const lines = palette.map((rgb, i) => {
    const [L, C, H] = rgbToOklch(rgb[0], rgb[1], rgb[2]);
    return `  --${getColorName(i)}: ${oklchToString(L, C, H)};`;
  }).join('\n');
  return `/* OKLCH — perceptually uniform color space */\n:root {\n${lines}\n}`;
};

/** Flat Lumina JSON (simple key→hex) */
const generateFlatJSON = (palette: RGB[]) => {
  const entries: Record<string, string> = {};
  palette.forEach((rgb, i) => {
    entries[getColorName(i)] = rgbToHex(rgb[0], rgb[1], rgb[2]);
  });
  return JSON.stringify(entries, null, 2);
};

/**
 * DTCG W3C Design Token Community Group format.
 * Spec: https://tr.designtokens.org/format/
 */
const generateDTCG = (palette: RGB[]) => {
  const tokens: Record<string, unknown> = {
    $schema: 'https://tr.designtokens.org/format/',
  };
  const colorGroup: Record<string, unknown> = {};
  palette.forEach((rgb, i) => {
    colorGroup[getColorName(i)] = {
      $value: rgbToHex(rgb[0], rgb[1], rgb[2]),
      $type: 'color',
      $description: `Generated by Lumina · color ${i + 1} of ${palette.length}`,
    };
  });
  tokens['color'] = colorGroup;
  return JSON.stringify(tokens, null, 2);
};

// ─── Component ────────────────────────────────────────────────────────────────

export const ExportPanel: React.FC<ExportPanelProps> = ({ palette }) => {
  const [activeTab, setActiveTab] = useState<TabId>('tailwind');
  const [copied, setCopied]       = useState(false);

  if (!palette || palette.length === 0) return null;

  const content =
    activeTab === 'tailwind' ? generateTailwind(palette) :
    activeTab === 'css'      ? generateCSS(palette)      :
    activeTab === 'oklch'    ? generateOKLCH(palette)    :
                               generateFlatJSON(palette);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  /** Download DTCG-compliant JSON file */
  const handleDTCGDownload = () => {
    const blob = new Blob([generateDTCG(palette)], { type: 'application/json' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = 'lumina-tokens.dtcg.json';
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabs: { id: TabId; label: string; icon: React.ElementType; activeClass: string }[] = [
    { id: 'tailwind', label: 'Tailwind',     icon: Code,       activeClass: 'text-sky-500 dark:text-sky-400' },
    { id: 'css',      label: 'CSS Vars',     icon: Paintbrush, activeClass: 'text-pink-500'                  },
    { id: 'oklch',    label: 'OKLCH',        icon: Atom,       activeClass: 'text-violet-400'                },
    { id: 'json',     label: 'JSON / Figma', icon: Braces,     activeClass: 'text-amber-500'                 },
  ];

  return (
    <div className="w-full mt-8">
      <div className="bg-white dark:bg-zinc-900 rounded-2xl border border-zinc-200 dark:border-zinc-800 overflow-hidden shadow-sm">

        {/* ── Tab bar ── */}
        <div className="flex items-center justify-between px-2 pt-2 bg-zinc-50 dark:bg-zinc-950 border-b border-zinc-200 dark:border-zinc-800 gap-2 flex-wrap">
          <div className="flex space-x-1 flex-wrap">
            {tabs.map(({ id, label, icon: Icon, activeClass }) => {
              const isActive = activeTab === id;
              return (
                <button
                  key={id}
                  onClick={() => setActiveTab(id)}
                  className={`flex items-center px-3.5 py-2 text-sm font-medium rounded-t-lg transition-all duration-150 whitespace-nowrap ${
                    isActive
                      ? `bg-white dark:bg-zinc-900 ${activeClass} border-t border-x border-zinc-200 dark:border-zinc-800 -mb-px`
                      : 'text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300 border-t border-x border-transparent'
                  }`}
                >
                  <Icon className="w-3.5 h-3.5 mr-1.5" />
                  {label}
                </button>
              );
            })}
          </div>

          {/* Right-side actions */}
          <div className="flex items-center gap-2 mb-2 mr-2">
            {/* DTCG Download */}
            <button
              onClick={handleDTCGDownload}
              title="Download DTCG-standard JSON for Figma / Style Dictionary"
              className="flex items-center px-3 py-1.5 text-xs font-medium bg-violet-600 hover:bg-violet-700 text-white rounded-md transition-colors gap-1.5 shadow-sm"
            >
              <Download className="w-3.5 h-3.5" />
              DTCG .json
            </button>

            {/* Copy code */}
            <button
              onClick={handleCopy}
              className="flex items-center px-3 py-1.5 text-xs font-medium bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700 text-zinc-700 dark:text-zinc-300 rounded-md transition-colors gap-1.5"
            >
              {copied
                ? <><Check className="w-3.5 h-3.5 text-green-500" />Copied!</>
                : <><Copy className="w-3.5 h-3.5" />Copy</>
              }
            </button>
          </div>
        </div>

        {/* ── Code block ── */}
        <div className="p-4 bg-zinc-950 text-zinc-100 overflow-x-auto">
          <pre className="font-mono text-sm leading-relaxed whitespace-pre">
            <code>{content}</code>
          </pre>
        </div>

        {/* ── Footer hints ── */}
        {activeTab === 'oklch' && (
          <div className="px-4 py-2.5 bg-zinc-950 border-t border-zinc-800 text-xs text-zinc-500 flex items-center gap-1.5">
            <Atom className="w-3 h-3 shrink-0 text-violet-400" />
            OKLCH is a perceptually uniform color space. Colors look more predictable across hue and lightness.
            Supported natively in modern browsers (Chrome 111+, Firefox 113+, Safari 15.4+).
          </div>
        )}
        {activeTab === 'json' && (
          <div className="px-4 py-2.5 bg-zinc-950 border-t border-zinc-800 text-xs text-zinc-500 flex items-center gap-1.5">
            <Braces className="w-3 h-3 shrink-0 text-amber-400" />
            Paste into Figma → Plugins → Figma Tokens. For the full W3C DTCG format, use the{' '}
            <button onClick={handleDTCGDownload} className="underline text-violet-400 hover:text-violet-300 transition-colors">
              Download DTCG .json
            </button>{' '}
            button above.
          </div>
        )}
      </div>
    </div>
  );
};
